import React from 'react';

const Disclosure: React.FC = () => (
  <section className="text-xs text-gray-500 space-y-3 pt-8 border-t border-gray-200">
    <p>DISCLOSURE: We are a professional review site that receives compensation from the companies whose products we review and recommend. We are independently owned and the opinions expressed here are our own. *All rates, fees, and terms are presented without guarantee and are subject to change by the provider. There is no guarantee that you will be approved for the rates, fees, or terms presented. The only way to determine your eligibility and any applicable rates, fees, or terms is to apply with the provider. Please review the provider’s terms and conditions for additional details.</p>
    <p>For example, if you were to receive a $10,000 loan with a 5-year term, your monthly payment might be $210.01 for a loan with a 9.5% APR. This example includes an estimated 5.00% origination fee. Your APR may be higher or lower depending on your creditworthiness, loan amount, loan term, and other factors. Some lenders may offer loans with APRs as low as 3.99% to 35.99%, and loan amounts ranging from $500 to $100,000. Loan terms generally range from 12 to 60 months. Not all consumers will be approved for a loan or for the lowest APR. Loan pre-qualification is not a loan approval and you must submit a full application to determine your eligibility. Pre-qualification may not be available to all lenders. Expedited funding may be available for some loans, but the actual time to receive your funds will depend on the lender and your bank.</p>
    <p>Our Top Picks: Our "Top Picks" are not representative of all lenders in the marketplace. We have evaluated the lenders in our review database and identified our "Top Picks" based on a variety of factors, including but not limited to, the lender's rates, fees, loan terms, and our own internal review. We are compensated by our "Top Picks," and our compensation may impact the order in which they appear. Our "Top Picks" are not intended to be an endorsement or recommendation of any of the lenders or their products or services. We encourage you to shop around and compare offers from multiple lenders to find the loan that's right for you.</p>
  </section>
);

export default Disclosure;